#! /bin/sh

bspc monitor -d '1' '2' '3' '4' '5' '6' 

bspc config border_width        3
bspc config window_gap          0
bspc config split_ratio         0.5
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_follows_pointer true
bspc config normal_border_color "#AAAAAA"
bspc config focused_border_color "#3966BB"
bspc config normal_frame_opacity 1.0
bspc config focused_frame_opacity 1.0
bspc config active_frame_opacity 1.0

#Output the needed variables to the tmp directory
rm -rf /tmp/bspwm 
mkdir /tmp/bspwm 

#the default window gap
echo "8" > /tmp/bspwm/window_gap

rulc -a 'class="BSPWM_FRAME"' 'frame=on'

killall compton 
compton --config ~/.config/compton.conf &
panel dzen2 & 
bspc config bottom_padding 60
tint2 &


#journal_path="/mnt/common/Documents/journal/"
#today="20"`date +"%y-%m-%d"`
#todays_journal=$journal_path$today".journal"
#urxvt -e nano $todays_journal &
#bspc window -d 'NOTES'


